In [1]:
import pandas as pd
import requests
import json

pd.set_option('display.max_columns', None)

In [2]:
url = "https://api.pluggy.ai/auth"

payload = {
    "clientId": "e3092229-0226-4439-b5b5-535a16dfeb42",
    "clientSecret": "TnzAyRxru9rTdoLOjQIePsoCTPJsAnPwXZFGwxAapbw"
}

headers = {
    "accept": "application/json",
    "content-type": "application/json"
}

api_key = requests.post(url,json=payload, headers=headers).json().get("apiKey")

In [10]:
print(f"API Key: {api_key}")

API Key: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMjVhNjA2ZTlkOWZlM2IzNmFkM2YzMzkzMDhjYTA5NGM6MmQzMzc5YWEwN2ZkMmQxN2NhOGRiMDMwNDY3OTkyMWEwZWIwMzYyMjI3Y2VmNzlkZmIwZmY3MzE0YzE4NGY0MDExODQyYmEzMjNhNWZkYjFlYzA4MzdmZjUzMWY0NTkxOWI2NGVkNjZlZmYxMmZhNjQ4M2EwZTQ0NDRiNzk2YTQ5NjBmYjQ4ZTVjYWIzMTI1M2VkNWI2MzUxODgyNDI4YSIsImlhdCI6MTc4OTI2MjMzMywiZXhwIjoxNzg5MjY5NTMzfQ.DSeBiOiq6ib81O5GWEHSLa6UWxIbD7hlitSWJvi-OrvKB2AC8MrakYacQtqjAh0QxGLAEZMIOvCFanY2PDZk3R62FLtMjYAM7uTH5PlAoH5kaF8n6GPyGFYMc1GK9gIDNDZdxmHH59wXDDLAYNsiAM2l29CHuoU_5Gy1u47Ef1GD48qaqCPS68vH40K-ZsRP1by_8kg1K7c6OzLr0uZ4bgiRFd0BHOQwnVybdqhmrXitdtGnWG85R_vue6WfZH3ysAJ9SNMz4bajrHrrgPnxZrD9JHTH2V-xS1ovUaxtX4XwNNa6PnQNjUZ2TmrN1JndOTLIMJTTTodiSI5gEgXMKQ

In [20]:
headers = {
    "X-API-KEY": api_key,
    "Content-Type": "application/json"
}

url = "https://api.pluggy.ai/items"

response = requests.get(url, headers=headers, json=payload,  params={"accountId": "e54de2cd-79ed-4be2-807e-f64bcde933d3"}).json().get("results")
print(f"Response: {response}")

Response: None

In [18]:
headers = {
    "X-API-KEY": api_key,
    "Content-Type": "application/json"
}

url = "https://api.pluggy.ai/v2/transactions"

response = requests.get(url, headers=headers, json=payload,  params={"accountId": "e54de2cd-79ed-4be2-807e-f64bcde933d3"}).json().get("results")

In [19]:
print(response)

[{'id': 'd8ae8028-9d5a-49b7-859e-0c29997f7e1a', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -9507.15, 'amountInAccountCurrency': None, 'date': '2026-07-19T15:20:23.854Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'ede79446-850f-4fc5-bc11-80726139db1f', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 9507.15, 'amountInAccountCurrency': None, 'date': '2026-07-19T15:19:41.213Z', 'category': 'Same person transfer', 'categoryId': '04000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': '00411128-8', 'branchNumber': '0020', 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': '208', 'routingNumberISPB': '30306294'}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'df93e824-25ab-4f72-b47e-45248ed1adc7', 'description': 'Transferência enviada|Amazon Serviços de Varejo do Brasil LTDA.', 'descriptionRaw': 'Transferência enviada|Amazon Serviços de Varejo do Brasil LTDA.', 'currencyCode': 'BRL', 'amount': -563.32, 'amountInAccountCurrency': None, 'date': '2026-07-12T18:22:20.474Z', 'category': 'Bookstore', 'categoryId': '08060000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': '1000826894-8', 'branchNumber': '0001', 'documentNumber': {'type': 'CNPJ', 'value': '15.436.940/0001-03'}, 'name': 'AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.', 'routingNumber': '383', 'routingNumberISPB': '21018182'}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': {'cnae': '4761001', 'cnpj': '15436940000103', 'category': 'Bookstore', 'businessName': 'AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.'}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '8c2e86c6-22f7-4c2b-9068-fc4f7c70a87c', 'description': 'Resgate RDB', 'descriptionRaw': 'Resgate RDB', 'currencyCode': 'BRL', 'amount': 563.32, 'amountInAccountCurrency': None, 'date': '2026-07-12T18:21:52.056Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': None, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '24f69692-b2ae-4438-96b0-f1f0a2e5cb94', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -12509.35, 'amountInAccountCurrency': None, 'date': '2026-07-01T11:35:45.759Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'e2311a90-8be4-4496-9056-e825611cc4ad', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 12509.35, 'amountInAccountCurrency': None, 'date': '2026-07-01T11:31:42.389Z', 'category': 'Same person transfer', 'categoryId': '04000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': '00411128-8', 'branchNumber': '0020', 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': '208', 'routingNumberISPB': '30306294'}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '415f1e79-8a59-4f8a-a118-d8b6f7e84832', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -3249.05, 'amountInAccountCurrency': None, 'date': '2026-06-17T12:28:36.060Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'e5ee0392-4838-4e92-9a9b-af013d49fa8e', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 3249.05, 'amountInAccountCurrency': None, 'date': '2026-06-03T14:03:13.051Z', 'category': 'Same person transfer', 'categoryId': '04000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': '00411128-8', 'branchNumber': '0020', 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': '208', 'routingNumberISPB': '30306294'}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '9b514686-f942-44a1-9209-f1425a98fd7f', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -4221.26, 'amountInAccountCurrency': None, 'date': '2026-04-06T21:04:44.715Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '6523599b-7b17-4e64-84d3-d1f6ffce4847', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 4221.26, 'amountInAccountCurrency': None, 'date': '2026-04-06T21:02:13.440Z', 'category': 'Same person transfer', 'categoryId': '04000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': '00411128-8', 'branchNumber': '0020', 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': '208', 'routingNumberISPB': '30306294'}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '1688d294-9ab5-406a-ac7a-7d5018782f7d', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -1000.87, 'amountInAccountCurrency': None, 'date': '2026-03-05T15:18:35.447Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'a8a392b0-56a3-493b-b203-9934a012f377', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 1000, 'amountInAccountCurrency': None, 'date': '2026-03-05T15:17:09.036Z', 'category': 'Same person transfer', 'categoryId': '04000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': '00411128-8', 'branchNumber': '0020', 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': '208', 'routingNumberISPB': '30306294'}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '4a5f3ca3-5e69-4cf3-898e-b10f92e35cd9', 'description': 'Transferência enviada|UNIAO NACIONAL DOS ESTUDANTES', 'descriptionRaw': 'Transferência enviada|UNIAO NACIONAL DOS ESTUDANTES', 'currencyCode': 'BRL', 'amount': -93.89, 'amountInAccountCurrency': None, 'date': '2026-03-04T17:14:31.569Z', 'category': 'Services', 'categoryId': '07000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': '00861434-1', 'branchNumber': '0002', 'documentNumber': {'type': 'CNPJ', 'value': '29.258.597/0002-31'}, 'name': 'UNIAO NACIONAL DOS ESTUDANTES', 'routingNumber': '401', 'routingNumberISPB': '15111975'}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': {'cnae': '9430800', 'cnpj': '29258597000231', 'category': 'Services', 'businessName': 'UNIAO NACIONAL DOS ESTUDANTES'}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '88f25223-288b-4593-8445-551a831e9f91', 'description': 'Resgate RDB', 'descriptionRaw': 'Resgate RDB', 'currencyCode': 'BRL', 'amount': 93.89, 'amountInAccountCurrency': None, 'date': '2026-03-04T17:14:04.537Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': None, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '3c1d3138-6a20-48d3-9b32-3e07a79f1913', 'description': 'Transferência enviada|DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S A', 'descriptionRaw': 'Transferência enviada|DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S A', 'currencyCode': 'BRL', 'amount': -89.13, 'amountInAccountCurrency': None, 'date': '2026-03-04T13:44:05.438Z', 'category': 'Services', 'categoryId': '07000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'PIX', 'reason': None, 'receiver': {'accountNumber': '00530166-0', 'branchNumber': '0001', 'documentNumber': {'type': 'CNPJ', 'value': '25.021.356/0001-32'}, 'name': 'DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S.A.', 'routingNumber': None, 'routingNumberISPB': '25021356'}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'PIX', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': {'cnae': '7490104', 'cnpj': '25021356000132', 'category': 'Services', 'businessName': 'DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S.A.'}, 'providerId': None, 'order': 2, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'd3265649-7f49-4516-bb43-c1764bb87892', 'description': 'Resgate RDB', 'descriptionRaw': 'Resgate RDB', 'currencyCode': 'BRL', 'amount': 90, 'amountInAccountCurrency': None, 'date': '2026-03-04T13:43:25.778Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': None, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'CREDIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 3, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': '2343f9be-e8e7-428e-a354-ab9f44d5b3bc', 'description': 'Aplicação RDB', 'descriptionRaw': 'Aplicação RDB', 'currencyCode': 'BRL', 'amount': -5000.71, 'amountInAccountCurrency': None, 'date': '2026-03-04T11:18:10.171Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'e54de2cd-79ed-4be2-807e-f64bcde933d3', 'providerCode': None, 'status': 'POSTED', 'paymentData': {'payer': {'accountNumber': None, 'branchNumber': None, 'documentNumber': {'type': 'CPF', 'value': '485.144.928-37'}, 'name': None, 'routingNumber': None, 'routingNumberISPB': None}, 'paymentMethod': 'OTHER', 'reason': None, 'receiver': None, 'receiverReferenceId': None, 'authenticationCode': None, 'referenceNumber': None, 'boletoMetadata': None}, 'type': 'DEBIT', 'operationType': 'RESGATE_APLIC_FINANCEIRA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': None, 'merchant': None, 'providerId': None, 'order': 4, 'createdAt': '2026-09-07T20:32:23.537Z', 'updatedAt': '2026-09-07T20:32:23.537Z'}, {'id': 'e3852a7e-9877-4e32-9f10-cf080d7fd17c', 'description': 'Transferência Recebida|Matheus Rocha Cardoso', 'descriptionRaw': 'Transferência Recebida|Matheus Rocha Cardoso', 'currencyCode': 'BRL', 'amount': 5000.71, 'amountInAccountCurrency': None, 'date': '2026-03-04T11:17:02.395Z', 'category': 'Same person transfer', 'categoryId': '04000000',

In [4]:
transactions_raw = pd.DataFrame([
    {chave: valor for chave, valor in item.items()}
    for item in response
])

transactions_raw.head(5)

,id,description,descriptionRaw,currencyCode,amount,amountInAccountCurrency,date,category,categoryId,balance,accountId,providerCode,status,paymentData,type,operationType,operationTypeAdditionalInfo,creditCardMetadata,merchant,providerId,order,createdAt,updatedAt
0,d8ae8028-9d5a-49b7-859e-0c29997f7e1a,Aplicação RDB,Aplicação RDB,BRL,-9507.15,None,2026-07-19T15:20:23.854Z,Investments,03000000,None,e54de2cd-79ed-4be2-807e-f64bcde933d3,None,POSTED,"{'payer': {'accountNumber': None, 'branchNumbe...",DEBIT,RESGATE_APLIC_FINANCEIRA,None,None,None,None,0,2026-09-07T20:32:23.537Z,2026-09-07T20:32:23.537Z
1,ede79446-850f-4fc5-bc11-80726139db1f,Transferência Recebida|Matheus Rocha Cardoso,Transferência Recebida|Matheus Rocha Cardoso,BRL,9507.15,None,2026-07-19T15:19:41.213Z,Same person transfer,04000000,None,e54de2cd-79ed-4be2-807e-f64bcde933d3,None,POSTED,"{'payer': {'accountNumber': '00411128-8', 'bra...",CREDIT,PIX,None,None,None,None,1,2026-09-07T20:32:23.537Z,2026-09-07T20:32:23.537Z
2,df93e824-25ab-4f72-b47e-45248ed1adc7,Transferência enviada|Amazon Serviços de Varej...,Transferência enviada|Amazon Serviços de Varej...,BRL,-563.32,None,2026-07-12T18:22:20.474Z,Bookstore,08060000,None,e54de2cd-79ed-4be2-807e-f64bcde933d3,None,POSTED,"{'payer': {'accountNumber': None, 'branchNumbe...",DEBIT,PIX,None,None,"{'cnae': '4761001', 'cnpj': '15436940000103', ...",None,0,2026-09-07T20:32:23.537Z,2026-09-07T20:32:23.537Z
3,8c2e86c6-22f7-4c2b-9068-fc4f7c70a87c,Resgate RDB,Resgate RDB,BRL,563.32,None,2026-07-12T18:21:52.056Z,Investments,03000000,None,e54de2cd-79ed-4be2-807e-f64bcde933d3,None,POSTED,"{'payer': None, 'paymentMethod': 'OTHER', 'rea...",CREDIT,RESGATE_APLIC_FINANCEIRA,None,None,None,None,1,2026-09-07T20:32:23.537Z,2026-09-07T20:32:23.537Z
4,24f69692-b2ae-4438-96b0-f1f0a2e5cb94,Aplicação RDB,Aplicação RDB,BRL,-12509.35,None,2026-07-01T11:35:45.759Z,Investments,03000000,None,e54de2cd-79ed-4be2-807e-f64bcde933d3,None,POSTED,"{'payer': {'accountNumber': None, 'branchNumbe...",DEBIT,RESGATE_APLIC_FINANCEIRA,None,None,None,None,0,2026-09-07T20:32:23.537Z,2026-09-07T20:32:23.537Z

In [5]:
transactions = transactions_raw[['id', 'description', 'amount', 'currencyCode', 'date', 'category', 'type', 'status', 'operationType', 'createdAt']]
transactions['bankName'] = 'NuBank'
transactions.head()

,id,description,amount,currencyCode,date,category,type,status,operationType,createdAt,bankName
0,d8ae8028-9d5a-49b7-859e-0c29997f7e1a,Aplicação RDB,-9507.15,BRL,2026-07-19T15:20:23.854Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank
1,ede79446-850f-4fc5-bc11-80726139db1f,Transferência Recebida|Matheus Rocha Cardoso,9507.15,BRL,2026-07-19T15:19:41.213Z,Same person transfer,CREDIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank
2,df93e824-25ab-4f72-b47e-45248ed1adc7,Transferência enviada|Amazon Serviços de Varej...,-563.32,BRL,2026-07-12T18:22:20.474Z,Bookstore,DEBIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank
3,8c2e86c6-22f7-4c2b-9068-fc4f7c70a87c,Resgate RDB,563.32,BRL,2026-07-12T18:21:52.056Z,Investments,CREDIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank
4,24f69692-b2ae-4438-96b0-f1f0a2e5cb94,Aplicação RDB,-12509.35,BRL,2026-07-01T11:35:45.759Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank

In [6]:
merchants = pd.json_normalize(transactions_raw.loc[~transactions_raw['merchant'].isnull()][['merchant']].drop_duplicates()['merchant'])
merchants = merchants.rename(columns={'category': 'merchantCategory', 'cnae': 'merchantCnae', 'cnpj': 'merchantCnpj', 'id': 'merchantId', 'businessName': 'merchantName'})

merchants.head(5)

,merchantCnae,merchantCnpj,merchantCategory,merchantName
2,4761001,15436940000103,Bookstore,AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.
12,9430800,29258597000231,Services,UNIAO NACIONAL DOS ESTUDANTES
14,7490104,25021356000132,Services,DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S.A.
20,6493000,48041735000190,Services,PORTO SEGURO ADMINISTRADORA DE CONSORCIOS LTDA
23,8112500,18328750000152,Housing,CONDOMINIO LIBER BOSQUE DOS BURITIS

In [7]:
transactions_final = transactions.join(merchants, how='left')
transactions_final.head(5)

,id,description,amount,currencyCode,date,category,type,status,operationType,createdAt,bankName,merchantCnae,merchantCnpj,merchantCategory,merchantName
0,d8ae8028-9d5a-49b7-859e-0c29997f7e1a,Aplicação RDB,-9507.15,BRL,2026-07-19T15:20:23.854Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
1,ede79446-850f-4fc5-bc11-80726139db1f,Transferência Recebida|Matheus Rocha Cardoso,9507.15,BRL,2026-07-19T15:19:41.213Z,Same person transfer,CREDIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
2,df93e824-25ab-4f72-b47e-45248ed1adc7,Transferência enviada|Amazon Serviços de Varej...,-563.32,BRL,2026-07-12T18:22:20.474Z,Bookstore,DEBIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank,4761001,15436940000103,Bookstore,AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.
3,8c2e86c6-22f7-4c2b-9068-fc4f7c70a87c,Resgate RDB,563.32,BRL,2026-07-12T18:21:52.056Z,Investments,CREDIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
4,24f69692-b2ae-4438-96b0-f1f0a2e5cb94,Aplicação RDB,-12509.35,BRL,2026-07-01T11:35:45.759Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN

In [8]:
transactions_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                48 non-null     str
 1   description       48 non-null     str
 2   amount            48 non-null     float64
 3   currencyCode      48 non-null     str
 4   date              48 non-null     str
 5   category          48 non-null     str
 6   type              48 non-null     str
 7   status            48 non-null     str
 8   operationType     48 non-null     str
 9   createdAt         48 non-null     str
 10  bankName          48 non-null     str
 11  merchantCnae      8 non-null      str
 12  merchantCnpj      8 non-null      str
 13  merchantCategory  8 non-null      str
 14  merchantName      8 non-null      str
dtypes: float64(1), str(14)
memory usage: 5.8 KB

In [9]:
transactions.to_csv('transactions.csv', index=False)